#9441 - redirect URI is required to be absolute
Prevent this exception:
  InvalidArgumentException: Redirect URI must be absolute in Google\Auth\OAuth2->setRedirectUri()